### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ouadie-lahdioui** [patternfly/patternfly-blog#2]
Hello everybody 👋 

I juste want to say that "Community" and "Download" links are broken, they return a 404 Not Found error :

<img width="699" alt="screen shot 2018-06-11 at 15 45 41" src="https://user-images.githubusercontent.com/2996203/41235204-88a970f4-6d8e-11e8-93a0-3cd279a901a6.png">

<img width="812" alt="screen shot 2018-06-11 at 15 44 25" src="https://user-images.githubusercontent.com/2996203/41235152-60a8cb0e-6d8e-11e8-8478-55cb6b3ff658.png">

Thank you,

**Comment by amarie401** [comment]
Hi! Thanks for pointing out this issue! I will take a look at it 👍

**Comment by amarie401** [comment]
There was a decision many weeks ago to remove the community and download links from patternfly.org. Those PR's can be found [here](https://github.com/patternfly/patternfly-org/pull/541) and [here](https://github.com/patternfly/patternfly-org/pull/562). So according to those changes, I went ahead and removed those links from the blog as well. The links should now be in sync with what is currently present on the site. FYI @LHinson 

Thanks for pointing this out! @ouadie-lahdioui

**Comment by amarie401** [comment]
The issue has been fixed, should we go ahead and close this issue? @LHinson

**Comment by ouadie-lahdioui** [comment]
Thank you
